// src/routes/contact/+page.svelte
<script>
	import { PORTFOLIO_NAME } from '$lib/constants';

	export let data;
	const { email, phone, instagram, image } = data.info.contact;
</script>

<svelte:head>
	<title>Contact | {PORTFOLIO_NAME}</title>
</svelte:head>

<section
	class="mx-auto flex flex-col-reverse gap-y-5 pb-20 lg:h-full lg:flex-row lg:gap-y-0 lg:pb-0"
>
	<ul
		class="flex flex-col place-content-center gap-y-5 px-2.5 font-serif text-6xl font-bold lg:w-1/2 lg:p-10 lg:text-7xl"
	>
		<li class="tw-animation hover:text-blue-700">
			<a href={`mailto:${email}`}>Email</a>
		</li>
		<li class="tw-animation hover:text-blue-700">
			<a href={`tel:${phone}`}>Teléfono</a>
		</li>
		<li class="tw-animation hover:text-blue-700">
			<a href={instagram} target="_blank" rel="”noopener noreferrer">Instagram</a>
		</li>
	</ul>
	<div class="flex w-full overflow-hidden lg:h-full lg:max-h-screen lg:w-1/2 lg:flex-col">
		<img src={image.url} alt={image.alt} class="object-cover" />
	</div>
</section>

// app/contact/page.tsx
import type { Metadata } from "next"
import Image from "next/image"

import { client } from "@/lib/graphql-client"
import { contactQuery } from "@/lib/graphql-queries"

export const revalidate = 60

export const metadata: Metadata = {
  title: "Contacto",
  description:
    "Muebles artesanos creados por Juan Serrano, carpintero y ebanista basado en Madrid.",
}

const getContactPage = async () => {
  const { infos }: { infos: any } = await client.request(contactQuery)

  return infos[0]
}

export default async function ContactPage() {
  const { contact } = await getContactPage()
  return (
    <section className="mx-auto grid min-h-screen grid-rows-2 overflow-y-auto md:h-screen md:grid-cols-2 md:grid-rows-1">
      <ul className="col-span-1 flex flex-col place-content-center gap-y-5 px-5 pb-28 pt-10 font-serif text-5xl font-bold md:w-1/2 md:px-10 md:py-0 md:text-7xl">
        <li className="tw-animation hover:text-blue-700">
          <a href={`mailto:${contact.email}`}>Email</a>
        </li>
        <li className="tw-animation hover:text-blue-700">
          <a href={`tel:${contact.phone}`}>Teléfono</a>
        </li>
        <li className="tw-animation hover:text-blue-700">
          <a
            href={contact.instagram}
            target="_blank"
            rel="”noopener noreferrer"
          >
            Instagram
          </a>
        </li>
      </ul>
      <div className="relative col-span-1 row-start-1 md:row-start-auto">
        <Image
          src={contact.image.url}
          alt="Hombre susteniendo una mesa de madera."
          width={960}
          height={960}
          priority
          className="h-auto w-full bg-blue-800 object-cover object-center"
        />
      </div>
    </section>
  )
}
