// src/routes/Card.svelte
<script>
	export let title = '';
	export let year = '';
	export let slug = '';
	export let url = '';
</script>

<a href={`/work/${slug}`} class="tw-animation relative flex min-w-full">
	<h2
		class="tw-vertical-text bg absolute flex items-baseline gap-x-2.5 bg-stone-50 bg-opacity-50 py-2.5 drop-shadow-lg backdrop-blur-lg"
	>
		<span class="inline-block text-lg font-bold uppercase tracking-wider lg:text-xl">
			{title}
		</span>
		<span class="inline-block text-base font-medium text-stone-700 lg:text-lg">
			{year}
		</span>
	</h2>
	<img src={url} alt={title} class="object-cover object-center" />
</a>

// components/projects/card.tsx
import Image from "next/image"
import Link from "next/link"

export const Card = ({ project }: { project: any }) => {
  return (
    <Link href={`/work/${project.slug}`} className="w-full flex-none">
      <h2 className="tw-vertical-text absolute z-20 flex items-baseline gap-x-2.5 whitespace-nowrap bg-stone-50/50 py-2.5 drop-shadow-lg backdrop-blur-lg">
        <span className="inline-block text-lg font-bold uppercase tracking-wider md:text-xl">
          {project.title}
        </span>
        <span className="inline-block text-base font-medium text-stone-700 md:text-lg">
          {project.year}
        </span>
      </h2>
      <Image
        src={project.images[0].url}
        alt={project.title}
        width={1080}
        height={1080}
        className="bg-blue-800 object-cover object-center"
      />
    </Link>
  )
}
